version = 1

[[annotations]]
path = ["src/*"]
precedence = "closest"
SPDX-FileCopyrightText = "Copyright (C) 2016-2025, by Arseny Kapoulkine (arseny.kapoulkine@gmail.com)"
SPDX-License-Identifier = "MIT"
