version = 1

[[annotations]]
path = ["tests/auto/cooked/data/*cooked*",
        "tests/auto/geometry_source/data/tetrahedron.cooked.tri",
        "tests/auto/heightfield_readd/data/hf.png",
        "tests/auto/heightfield/data/hf.png",
        "tests/auto/physicsscene/data/hf.png",
        "tests/auto/physicsscene/data/hf.png",
        "tests/manual/convexmesh/qt_logo_rect.png",
        "tests/manual/convexmesh/maps/heightfield.png",
        "tests/baseline/data/*.png",
        "tests/baseline/data/*.qml",
        "tests/manual/charactercontroller/meshes/*.mesh",
        "tests/manual/convexmesh/meshes/*.mesh"]
precedence = "closest"
comment = "test"
SPDX-FileCopyrightText = "Copyright (C) 2024 The Qt Company Ltd."
SPDX-License-Identifier = "LicenseRef-Qt-Commercial OR GPL-3.0-only"

[[annotations]]
path = ["src/quick3dphysics/designer/images/*.png"]
precedence = "closest"
comment = "module and plugin"
SPDX-FileCopyrightText = "Copyright (C) 2024 The Qt Company Ltd."
SPDX-License-Identifier = "LicenseRef-Qt-Commercial OR GPL-3.0-only"

[[annotations]]
path = ["**CMakeLists.txt", ".cmake.conf", "**.yaml",
        "coin/axivion/ci_config_linux.json", "**.pri",
        "configure.json", ".tag"]
precedence = "closest"
comment = "build system"
SPDX-FileCopyrightText = "Copyright (C) 2024 The Qt Company Ltd."
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = ["**/.gitattributes", "**.gitignore", "**.gitreview", "tests/baseline/data/Ignore",
        "**.clang-format"]
precedence = "closest"
comment = "infrastructure"
SPDX-FileCopyrightText = "Copyright (C) 2024 The Qt Company Ltd."
SPDX-License-Identifier = "LicenseRef-Qt-Commercial OR BSD-3-Clause"

[[annotations]]
path = ["examples/**"]
comment = "this must be after the build system table because example and snippets take precedence over build system"
precedence = "closest"
SPDX-FileCopyrightText = "Copyright (C) 2024 The Qt Company Ltd."
SPDX-License-Identifier = "LicenseRef-Qt-Commercial OR BSD-3-Clause"

[[annotations]]
path = ["**/doc/images/**", "**/README*", "**.qdocconf", "**.metainfo"]
comment = "documentation"
precedence = "closest"
SPDX-FileCopyrightText = "Copyright (C) 2024 The Qt Company Ltd."
SPDX-License-Identifier = "LicenseRef-Qt-Commercial OR GFDL-1.3-no-invariants-only"

[[annotations]]
path = ["**.toml", "licenseRule.json"]
comment = "infrastructure"
precedence = "override"
SPDX-FileCopyrightText = "Copyright (C) 2024 The Qt Company Ltd."
SPDX-License-Identifier = "LicenseRef-Qt-Commercial OR BSD-3-Clause"

[[annotations]]
path = ["**/qt_attribution.json"]
comment = "documentation"
precedence = "override"
SPDX-FileCopyrightText = "Copyright (C) 2024 The Qt Company Ltd."
SPDX-License-Identifier = "LicenseRef-Qt-Commercial OR GFDL-1.3-no-invariants-only"

[[annotations]]
path = ["tests/baseline/shared/qwidgetbaselinetest.cpp",
        "tests/baseline/shared/baselineprotocol.cpp",
        "tests/baseline/shared/qwidgetbaselinetest.cpp"]
precedence = "override"
comment = "reuse can't parse those files."
SPDX-FileCopyrightText = "Copyright (C) 2021 The Qt Company Ltd."
SPDX-License-Identifier = "LicenseRef-Qt-Commercial OR GPL-3.0-only"

[[annotations]]
path = ["tests/manual/charactercontroller/maps/OpenfootageNET_lowerAustria01-512.hdr"]
precedence = "override"
SPDX-FileCopyrightText = "https://www.openfootage.net/hdri-360-lower-austria/"
SPDX-License-Identifier = "CC-BY-4.0"
